#+title: Unelaborated Ideas

An idea dump with minimal or no explanation. Unsubstantiated drivel.

* Systems

- Energy is fundamental.
- Systems that only consume are unsustainable. There is a problem if systems cannot produce.
- Maximize production, minimize consumption.
- Do not settle for mass produced mediocrity. Strive for excellence.
- I think there should be a progressive efficiency tax on scarce resources. It will help curb mass produced mediocrity using those resources and improve general access to them.
- Ideally, the money supply should match the value of the supply of our accumulated assets to keep prices relatively stable. Expanding the money supply too quickly (usually money printing) leads to inflation. That money simultaneously funds government programs and devalues the purchasing power of existing money. The inflation associated with money printing could be seen as a tax.
- The Achilles heel of cryptocurrencies is their costly energy consumption. If the average household paid their energy bills with crypto, a significant part of their bill would be in the cost of the transaction itself. Crypto is not appropriate for everyday transactions. I feel confident that crypto has a place in high-value transactions and is here to stay.

* Urban Planning

- It might be interesting to consider the parallels between urban planning and chip design.
- I want to make it easier for local farming and farmers to access urban markets and amenities by building rail lines for passengers and produce.
- Cities should be built pedestrian first.
- Vertical zoning would be interesting to explore. Or maybe I just want more ground floor retail.
- Sentencing someone to prison is an expense for tax payers yet the benefits of the sentence are almost always personal. I do not think it is fair that costs are socialized and benefits are privatized. I think community service needs to play a bigger role in prison systems so there is a tangible social benefit for the many.

* Health And Physiology

- Don't hesitate to administer local antibiotics. Systemic antibiotics are the ones to worry about.
- Learning to eat at maintenance is a prerequisite to bulking and cutting.
- Autoimmune and allergy symptoms decrease learning effectiveness. In some cases, learning may be stalled until symptoms are eliminated. Learning isn't limited to the academic sense. It includes learning motor skills, emotional skills, etc. Students without autoimmune and allergy symptoms have the advantage of learning more effectively, saving them both time and effort. I would love to see studies that test this.
- Cold hands and feet? Heat your core first.

* Thought And Psychology

- A great way to have no personal stories to tell is to hold the belief that "stories must be some grand, life changing epic". Oftentimes, I ended up in situations where ordinary stories are appropriate. However, that was challenging for me, because in accordance with the belief, I easily forgot my ordinary experiences. I didn't see the value in them. But I still wanted to tell compelling stories. Something needed to change, so I proposed a counter belief: "my ordinary experiences have value and they should be shared". While I can't do anything about the unborn stories of the past, I hope that by carrying the new belief forward, I'll have at least one story to tell.
- Names obscure. Names form a facade which hide truth and understanding.
- A home is a metaphorical place where you can build things that are important to you. It's not simply a place; it's a process that puts you at the center.
- Creating beauty is more beautiful than simply having it.
- I think passing down an evolving book of values might be a good idea. It would help each child figure out what it means to be a member of their family or community. I would like to imagine that citing specific values is as easy as citing mathematical theorems.
- I think there is something significant with having the ability to distill complex ideas to your target audience. Tom Bilyeu, Linus Sebastian, and Thomas DeLauer are three content creators who have explicitly credited this ability to their success.
- What happens when we receive contradicting information? If the senses are contradicting, then we might feel sick. If people in a group are contradicting, then a corresponding "sickness" may cause conflict and isolation. Our biology significantly biases how we process contradicting information. It takes considerable skill and effort to process contradicting information in a context effective manner.
- The next task should be split until there is high confidence that it can be completed in the next available time. If your next available time is 30 minutes, figure what you can complete within 30 minutes. The key is confidence. Confidence leads to action; action leads to results; and results lead to learnings. Those learnings will change your feelings about the task the next time you encounter it.
- Human thinking cannot be modelled with logic alone. Emotion is essential. Emotional logic is sufficient for modelling human behavior.

* Art

- Gesture is a flow that connects shapes. The dual of gesture is shape; the dual of shape is gesture.
