#+title: Reflections on the Monogatari Series

* Intro

I want to critically read the Monogatari Series. My raison d'être for learning Japanese. I never expected that I would be using critical reading skills voluntarily yet here I am. Leisurely deliberating the meanings of things is actually quite meditative.

** Scope

I plan to read all the canon stories. There's a bunch of short stories outside of the light novels so tracking which ones I still need to read is not simple. Luckily, it seems like someone from r/araragi has already compiled a list.

List of stories: https://redd.it/5t7kcq

* 化物語 ／ Bakemonogatari

** ひたぎクラブ ／ Hitagi Crab

*** 001

The narrator describes Senjougahara Hitagi's distant or perhaps weightless relationship with school. She's like a cloistered princess (深窓の令嬢) confined to the pages of her books. She seems like the type who reads whatever is in reach (濫読派). Outside of academics, she's a non-interactable character with a fleeting (儚げ) existence.

The narrator was somehow familiar enough with the top academic rankings to recognize patterns in them. Why would he bother looking up at the top ranks if his grades were far from it? It seems like academic performance is important to him in some way.

The narrator mentions that school is a strange place where people without friends end up forming their own circles. I'm pretty sure this is just a human thing to do and this would happen anywhere, not just school.

The narrator claims that Senjougahara's situation is nothing to worry about. After all, very few if any meaningful connections made in school will last past school. With the passage of time, the school experience will become a blur of memories. The narrator's points are valid but I disagree with him. Sure, living invisibly might turn out okay, but it will be no better than okay. I think most people want to strive for more than okay. To do that, they must become more than themselves which means assimilating and interacting with the outside world in meaningful ways.

The narrator mentions that he was a loner up until the end of the prior school year. The narrator references spring break and Golden Week as 地獄 (hell) and 絵空事 (fantasy) respectively.

When the narrator encounters Senjougahara, he simultaneously feels the weightlessness in her body and finds salience in her existence. Weight, under the force of gravity, tethers people to the world. A lack of it could explain Senjougahara's detached existence. Contradicting her weightlessness, she falls into the narrator and becomes a more significant existence to him.

*** 002

*** 003

*** 004

*** 005

*** 006

*** 007

*** 008

** まよいマイマイ ／ Mayoi Snail
