#+title: Speaking

* V0001

Content: I want to get better at speaking on video but I don't have a lot of time. Here is what I'm going to do. Intentional practice. Practice and review loop. I hope to become good enough that I can enjoy watching myself while still being critical and reflective.

Look: Please stay still. Both the body and the head.

Sound: Yayaya. I wish my voice was smoother.

Feel: At least I moved less. I'm still moving a bit too much unintentionally. The content is all over the place. It does feel like my voice is clearer when I'm am standing still. I guess there is a grounding effect that makes my voice more solid when my body is under control.

* V0002

Content: I'm talking about fasting since I have made a change recently. I want to keep it simple. What are my goals? I want to make sure I am healthy. Emphasize the change. (1) I'm changing my fasting regime. (2) I want to see better health results. (3) I'm afraid that fasting might be hurting me. (4) I was doing 16-8. (5) Now I want try 12-12.

Look: I need to look interested in what I'm talking about. I may have forgotten to smile. My face seemed extremely bored. The movements are still kind of random too.

Sound: It sounds a bit more interesting. I think sounds okay. It doesn't really draw me in though.

Feel: I think I'm at a loss of words. I should focus more on organizing so I'm basically just reading from them.

* V0003

Content: I guess I'm going to talk about Epstein today. The files were released. How do I feel about them? I don't care yet I'm talking about it. More like I don't want to talk about it. Maybe this is what I'm going to talk about.

Look: I still move around a bit too much.

Sound: I really don't like I remind myself of a certain react streamer. I think it has something to do with my cadence. I think it is the stop go stop go pattern that is too repetitive. Let's dry to vary the cadence.

Feel: I feel uncertain. Not sure where I'm going. Let's try iron out the contents a bit more.

Open with the big news. BUT shift to my observation.

I forgot could use an LLM for content. Even to write a script.
